### ISSUE TITLE
Add images of proposed designs

### ISSUE THREAD

**Issue by nikhil-RGB** [nikhil-RGB/srm_laundry#2]
### Description

- @chandramasaha has created tentative designs of the screens in the project.
- She will be uploading the images/screenshots of the screens rather than the original private figma file.

**Comment by chandramasaha** [comment]
![Light](https://github.com/nikhil-RGB/srm_laundry/assets/97869414/fd525709-17f8-418b-b0d7-3d8c3dc9a899)
![Dark](https://github.com/nikhil-RGB/srm_laundry/assets/97869414/efb1737d-64d9-4f12-946e-cedd0e99cd78)

**Comment by chandramasaha** [comment]
The design files have been added for both light & dark variable modes.

**Comment by nikhil-RGB** [comment]
### Description:

- @chandramasaha  You were supposed to upload the images to the repository, not within a comment on this issue.
